// Code generated by "stringer -type=Compatibility"; DO NOT EDIT

package schemaregistry

import "fmt"

const _Compatibility_name = "NoneFullForwardBackward"

var _Compatibility_index = [...]uint8{0, 4, 8, 15, 23}

func (i Compatibility) String() string {
	if i < 0 || i >= Compatibility(len(_Compatibility_index)-1) {
		return fmt.Sprintf("Compatibility(%d)", i)
	}
	return _Compatibility_name[_Compatibility_index[i]:_Compatibility_index[i+1]]
}
